[package]
name = "x1b"
version = "0.2.2"
authors = ["serprex"]
repository = "https://github.com/serprex/x1b"
description = "State tracker for 0x1b terminal escape codes. Also gives random characters names."
license = "MIT"

[dependencies]
bitflags = "0.7.0"
fnv = "1.0.3"
