[package]
name = "x1b"
version = "0.1.0"
authors = ["serprex"]
repository = "https://github.com/serprex/1xb"
description = "State tracker for 0x1b terminal escape codes. Also gives random characters names."
license = "MIT"

[dependencies]
bitflags = "0.4.0"
